In [11]:
import pandas as pd
import numpy as np
import ast  # For safely parsing string lists

df=pd.read_csv('pubmed_raw_data.csv')

In [13]:
print("Original shape:", df.shape)
print("\nColumns:", df.columns.tolist())
df

Original shape: (32554, 11)

Columns: ['ingredient', 'pmid', 'title', 'year', 'journal', 'diseases_mentioned', 'mesh_disease_terms', 'relationship_type', 'key_findings', 'authors', 'pubmed_url']

,ingredient,pmid,title,year,journal,diseases_mentioned,mesh_disease_terms,relationship_type,key_findings,authors,pubmed_url
0,protein,41390803,Association between triglyceride-glucose index...,2025,Cardiovascular diabetology,"diabetes, insulin resistance, cardiovascular d...",NaN,Risk Factor,The results indicated that elevated TyG-ABSI v...,"Xinyi Shao, Zhaofu Tan, Lifu Sun",https://pubmed.ncbi.nlm.nih.gov/41390803/
1,protein,41390778,Multi-task learning identifies shared genetic ...,2025,Scientific reports,alzheimer,NaN,Risk Factor,We analyzed electronic health records from UCL...,"Mingzhou Fu, Thai Tran, Bogdan Pasaniuc",https://pubmed.ncbi.nlm.nih.gov/41390778/
2,protein,41390701,Obesity concurrent with gestational diabetes m...,2025,Scientific reports,"diabetes, obesity, diabetes mellitus",NaN,Risk Factor,"Of note, proximity ligation assay (PLA) reveal...","Ruofan Wang, Jianying Liu, Qian Li",https://pubmed.ncbi.nlm.nih.gov/41390701/
3,protein,41390575,The RNA-binding protein CPEB1 marks healthy ad...,2025,Scientific reports,"diabetes, type 2 diabetes",NaN,Associated/Neutral,See full abstract for details,"Sutichot D Nimkulrat, Matthew R Wagner, Bayley...",https://pubmed.ncbi.nlm.nih.gov/41390575/
4,protein,41390442,Genetic insights into 5-LOX-activating protein...,2025,Human genomics,"inflammation, cardiovascular disease, stroke, ...",NaN,Associated/Neutral,The 5-lipoxygenase-activating protein (FLAP) i...,"Katharina Rataj, Ulrike Garscha",https://pubmed.ncbi.nlm.nih.gov/41390442/
...,...,...,...,...,...,...,...,...,...,...,...
32549,whole grain,38102063,The Southern European Atlantic diet and all-ca...,2024,European journal of preventive cardiology,"cardiovascular disease, cancer","Neoplasms, Cardiovascular Diseases",Risk Factor,See full abstract for details,"Adrián Carballo-Casla, Denes Stefler, Rosario ...",https://pubmed.ncbi.nlm.nih.gov/38102063/
32550,whole grain,38068801,A Narrative Review on Strategies for the Rever...,2023,Nutrients,diabetes,NaN,Risk Factor,See full abstract for details,"Mariangela Rondanelli, Gaetan Claude Barrile, ...",https://pubmed.ncbi.nlm.nih.gov/38068801/
32551,whole grain,38068763,Analysis of the Efficacy of Diet and Short-Ter...,2023,Nutrients,NaN,"Depression, Obesity, Morbid",Protective/Beneficial,(3) Results: Depressive symptoms were observed...,"Natalia Komorniak, Mariusz Kaczmarczyk, Igor Ł...",https://pubmed.ncbi.nlm.nih.gov/38068763/
32552,whole grain,38010908,Association between whole-grain consumption an...,2023,Food & function,inflammation,Inflammation,Associated/Neutral,No abstract available,"Ge Meng, Jiping Yao, Jiaoyang Li",https://pubmed.ncbi.nlm.nih.gov/38010908/
32553,whole grain,38007158,Molecular mechanism of microRNA-mediated hypog...,2024,Gene,"diabetes, type 2 diabetes, diabetes mellitus","Diabetes Mellitus, Type 2, Diabetes Mellitus, ...",Associated/Neutral,Our results showed that ten differentially exp...,"Mengyuan Qin, Xin Ren, Min Zhang",https://pubmed.ncbi.nlm.nih.gov/38007158/

In [14]:
print("\nNull values per column:")
print(df.isnull().sum())

Null values per column:
ingredient                0
pmid                      0
title                   171
year                      0
journal                   0
diseases_mentioned     1827
mesh_disease_terms    18474
relationship_type         0
key_findings              0
authors                  22
pubmed_url                0
dtype: int64

In [17]:
critical_cols = ['authors', 'title','diseases_mentioned']  # Add more if needed, e.g., 'title'
df = df.dropna(subset=critical_cols)

In [18]:
print(df.isnull().sum())

ingredient                0
pmid                      0
title                     0
year                      0
journal                   0
diseases_mentioned        0
mesh_disease_terms    18375
relationship_type         0
key_findings              0
authors                   0
pubmed_url                0
dtype: int64

In [19]:
text_cols = [ 'mesh_disease_terms']
df[text_cols] = df[text_cols].fillna('')

In [21]:
print(df.isnull().sum())

ingredient            0
pmid                  0
title                 0
year                  0
journal               0
diseases_mentioned    0
mesh_disease_terms    0
relationship_type     0
key_findings          0
authors               0
pubmed_url            0
dtype: int64

In [23]:
str_cols = df.select_dtypes(include='object').columns
str_cols

Index(['ingredient', 'title', 'journal', 'diseases_mentioned',
       'mesh_disease_terms', 'relationship_type', 'key_findings', 'authors',
       'pubmed_url'],
      dtype='object')

In [24]:
df[str_cols] = df[str_cols].apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [25]:
df[str_cols] = df[str_cols].apply(lambda x: x.str.replace(r'\s+', ' ', regex=True) if x.dtype == "object" else x)

In [27]:
print("\nFinal shape:", df.shape)
print("\nFinal null check:")
print(df.isnull().sum())
print("\nFirst 5 rows after cleaning:")
df.head()

Final shape: (30567, 11)

Final null check:
ingredient            0
pmid                  0
title                 0
year                  0
journal               0
diseases_mentioned    0
mesh_disease_terms    0
relationship_type     0
key_findings          0
authors               0
pubmed_url            0
dtype: int64

First 5 rows after cleaning:

,ingredient,pmid,title,year,journal,diseases_mentioned,mesh_disease_terms,relationship_type,key_findings,authors,pubmed_url
0,protein,41390803,Association between triglyceride-glucose index...,2025,Cardiovascular diabetology,"diabetes, insulin resistance, cardiovascular d...",,Risk Factor,The results indicated that elevated TyG-ABSI v...,"Xinyi Shao, Zhaofu Tan, Lifu Sun",https://pubmed.ncbi.nlm.nih.gov/41390803/
1,protein,41390778,Multi-task learning identifies shared genetic ...,2025,Scientific reports,alzheimer,,Risk Factor,We analyzed electronic health records from UCL...,"Mingzhou Fu, Thai Tran, Bogdan Pasaniuc",https://pubmed.ncbi.nlm.nih.gov/41390778/
2,protein,41390701,Obesity concurrent with gestational diabetes m...,2025,Scientific reports,"diabetes, obesity, diabetes mellitus",,Risk Factor,"Of note, proximity ligation assay (PLA) reveal...","Ruofan Wang, Jianying Liu, Qian Li",https://pubmed.ncbi.nlm.nih.gov/41390701/
3,protein,41390575,The RNA-binding protein CPEB1 marks healthy ad...,2025,Scientific reports,"diabetes, type 2 diabetes",,Associated/Neutral,See full abstract for details,"Sutichot D Nimkulrat, Matthew R Wagner, Bayley...",https://pubmed.ncbi.nlm.nih.gov/41390575/
4,protein,41390442,Genetic insights into 5-LOX-activating protein...,2025,Human genomics,"inflammation, cardiovascular disease, stroke, ...",,Associated/Neutral,The 5-lipoxygenase-activating protein (FLAP) i...,"Katharina Rataj, Ulrike Garscha",https://pubmed.ncbi.nlm.nih.gov/41390442/

In [28]:
output_file = 'Preprocessed_pubmed_data.csv'
df.to_csv(output_file, index=False)
print(f"\nCleaned data saved to {output_file}")

Cleaned data saved to Preprocessed_pubmed_data.csv