In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
food = pd.read_csv("D:/Downloads/Research/Data/raw/usda_fdc/food.csv",low_memory=False)

In [4]:
food.head()

,fdc_id,data_type,description,food_category_id,publication_date
0,1105904,branded_food,WESSON Vegetable Oil 1 GAL,Oils Edible,2020-11-13
1,1105905,branded_food,SWANSON BROTH BEEF,Herbs/Spices/Extracts,2020-11-13
2,1105906,branded_food,CAMPBELL'S SLOW KETTLE SOUP CLAM CHOWDER,Prepared Soups,2020-11-13
3,1105907,branded_food,CAMPBELL'S SLOW KETTLE SOUP CHEESE BROCCOLI,Prepared Soups,2020-11-13
4,1105898,experimental_food,Discrepancy between the Atwater factor predict...,NaN,2020-10-30

In [5]:
branded = pd.read_csv("D:/Downloads/Research/Data/raw/usda_fdc/branded_food.csv",low_memory=False)

In [6]:
branded.head()

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,...,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description,material_code
0,1105904,Richardson Oilseed Products (US) Limited,NaN,NaN,00027000612323,Vegetable Oil,NaN,15.0,ml,1 Tbsp (15 ml),...,GDSN,NaN,2020-10-02,2020-11-13,United States,NaN,NaN,NaN,NaN,NaN
1,1105905,CAMPBELL SOUP COMPANY,NaN,NaN,00051000198808,"INGREDIENTS: BEEF STOCK, CONTAINS LESS THAN 2%...",NaN,240.0,ml,Amount per serving,...,GDSN,NaN,2020-09-12,2020-11-13,United States,NaN,NaN,NaN,NaN,NaN
2,1105906,CAMPBELL SOUP COMPANY,NaN,NaN,00051000213273,"INGREDIENTS: CLAM STOCK, POTATOES, CLAMS, CREA...",NaN,440.0,g,PER CONTAINER,...,GDSN,NaN,2020-09-01,2020-11-13,United States,NaN,NaN,NaN,NaN,NaN
3,1105907,CAMPBELL SOUP COMPANY,NaN,NaN,00051000213303,"INGREDIENTS: WATER, CREAM, BROCCOLI, CELERY, V...",NaN,440.0,g,PER CONTAINER,...,GDSN,NaN,2020-09-01,2020-11-13,United States,NaN,NaN,NaN,NaN,NaN
4,1105908,CAMPBELL SOUP COMPANY,NaN,NaN,00051000224637,"INGREDIENTS: CHICKEN STOCK, CONTAINS LESS THAN...",NaN,240.0,ml,Amount per Serving,...,GDSN,NaN,2020-10-03,2020-11-13,United States,NaN,NaN,NaN,NaN,NaN

In [7]:
print("Food table shape:", food.shape)

Food table shape: (2064912, 5)

In [8]:
print("Branded food shape:", branded.shape)

Branded food shape: (1977398, 21)

In [13]:
print("\nFood columns:\n")
print(branded.columns.tolist())

Food columns:

['fdc_id', 'brand_owner', 'brand_name', 'subbrand_name', 'gtin_upc', 'ingredients', 'not_a_significant_source_of', 'serving_size', 'serving_size_unit', 'household_serving_fulltext', 'branded_food_category', 'data_source', 'package_weight', 'modified_date', 'available_date', 'market_country', 'discontinued_date', 'preparation_state_code', 'trade_channel', 'short_description', 'material_code']

In [14]:
print("\nMissing values in food.csv\n")
print(food.isnull().sum())

Missing values in food.csv

fdc_id                  0
data_type               0
description             9
food_category_id    14475
publication_date        0
dtype: int64

In [16]:
print("\nMissing values in branded_food.csv\n")
print(branded.isnull().sum())

Missing values in branded_food.csv

fdc_id                               0
brand_owner                      17232
brand_name                      544896
subbrand_name                  1871607
gtin_upc                             0
ingredients                       5373
not_a_significant_source_of    1897783
serving_size                     10753
serving_size_unit                18998
household_serving_fulltext       41309
branded_food_category            10630
data_source                          0
package_weight                 1133565
modified_date                       20
available_date                       0
market_country                       0
discontinued_date              1974152
preparation_state_code         1895488
trade_channel                  1943460
short_description              1895391
material_code                  1976075
dtype: int64

In [17]:
branded["ingredients"] = branded["ingredients"].fillna("No ingredients listed")

In [18]:
print("After filling:", branded["ingredients"].isnull().sum())

After filling: 0

In [19]:
branded["brand_owner"] = branded["brand_owner"].fillna("Unknown")
branded["brand_name"] = branded["brand_name"].fillna("Unknown")

In [22]:
print("After filling:", branded["brand_name"].isnull().sum())
print("After filling:", branded["brand_owner"].isnull().sum())

After filling: 0
After filling: 0

In [23]:
print("\nDuplicate rows in branded:", branded.duplicated().sum())

Duplicate rows in branded: 0

In [25]:
branded["ingredients"] = branded["ingredients"].str.upper()
branded["ingredients"] = branded["ingredients"].str.replace("INGREDIENTS:", "")
branded["ingredients"] = branded["ingredients"].str.replace("CONTAINS.*", "", regex=True)
branded["ingredients"] = branded["ingredients"].str.replace(r"\(.*?\)", "", regex=True)

In [26]:
branded.head()

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,...,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description,material_code
0,1105904,Richardson Oilseed Products (US) Limited,Unknown,NaN,00027000612323,VEGETABLE OIL,NaN,15.0,ml,1 Tbsp (15 ml),...,GDSN,NaN,2020-10-02,2020-11-13,United States,NaN,NaN,NaN,NaN,NaN
1,1105905,CAMPBELL SOUP COMPANY,Unknown,NaN,00051000198808,"BEEF STOCK,",NaN,240.0,ml,Amount per serving,...,GDSN,NaN,2020-09-12,2020-11-13,United States,NaN,NaN,NaN,NaN,NaN
2,1105906,CAMPBELL SOUP COMPANY,Unknown,NaN,00051000213273,"CLAM STOCK, POTATOES, CLAMS, CREAM, VEGETABLE...",NaN,440.0,g,PER CONTAINER,...,GDSN,NaN,2020-09-01,2020-11-13,United States,NaN,NaN,NaN,NaN,NaN
3,1105907,CAMPBELL SOUP COMPANY,Unknown,NaN,00051000213303,"WATER, CREAM, BROCCOLI, CELERY, VEGETABLE OIL...",NaN,440.0,g,PER CONTAINER,...,GDSN,NaN,2020-09-01,2020-11-13,United States,NaN,NaN,NaN,NaN,NaN
4,1105908,CAMPBELL SOUP COMPANY,Unknown,NaN,00051000224637,"CHICKEN STOCK,",NaN,240.0,ml,Amount per Serving,...,GDSN,NaN,2020-10-03,2020-11-13,United States,NaN,NaN,NaN,NaN,NaN

In [27]:
branded["ingredient_list"] = branded["ingredients"].str.split(",")

In [28]:
branded["ingredient_list"]

0                                            [VEGETABLE OIL]
1                                           [ BEEF STOCK,  ]
2          [ CLAM STOCK,  POTATOES,  CLAMS,  CREAM,  VEGE...
3          [ WATER,  CREAM,  BROCCOLI,  CELERY,  VEGETABL...
4                                        [ CHICKEN STOCK,  ]
                                 ...
1977393            [CORNISH HENS WITHOUT NECKS AND GIBLETS.]
1977394      [WHOLE CORNISH HENS WITHOUT NECKS AND GIBLETS.]
1977395                   [CHICKEN WING SECTIONS,  WATER,  ]
1977396    [PUMPKIN SEED KERNELS,  SEA SALT,  HIGH OLEIC ...
1977397    [YOGURT,  LOW FAT,  SUMMERBERRY:  CULTURED PAS...
Name: ingredient_list, Length: 1977398, dtype: object

In [29]:
branded["ingredient_list"] = branded["ingredient_list"].apply(
    lambda x: [i.strip() for i in x if i.strip() and len(i.strip()) > 1] if isinstance(x, list) else []
)

In [30]:
final_data = branded[["fdc_id", "brand_owner", "branded_food_category", "ingredient_list"]].copy()

In [31]:
final_data = final_data.merge(food[["fdc_id", "description"]], on="fdc_id", how="left")

In [32]:
final_data

,fdc_id,brand_owner,branded_food_category,ingredient_list,description
0,1105904,Richardson Oilseed Products (US) Limited,Oils Edible,[VEGETABLE OIL],WESSON Vegetable Oil 1 GAL
1,1105905,CAMPBELL SOUP COMPANY,Herbs/Spices/Extracts,[BEEF STOCK],SWANSON BROTH BEEF
2,1105906,CAMPBELL SOUP COMPANY,Prepared Soups,"[CLAM STOCK, POTATOES, CLAMS, CREAM, VEGETABLE...",CAMPBELL'S SLOW KETTLE SOUP CLAM CHOWDER
3,1105907,CAMPBELL SOUP COMPANY,Prepared Soups,"[WATER, CREAM, BROCCOLI, CELERY, VEGETABLE OIL...",CAMPBELL'S SLOW KETTLE SOUP CHEESE BROCCOLI
4,1105908,CAMPBELL SOUP COMPANY,Herbs/Spices/Extracts,[CHICKEN STOCK],SWANSON BROTH CHICKEN
...,...,...,...,...,...
1977393,2725768,Tyson Foods Inc.,Meat/Poultry/Other Animals - Prepared/Processed,[CORNISH HENS WITHOUT NECKS AND GIBLETS.],"Tyson Uncooked Cornish Hens, 24 Pieces, 28.5 Lb."
1977394,2725769,Tyson Foods Inc.,Meat/Poultry/Other Animals - Prepared/Processed,[WHOLE CORNISH HENS WITHOUT NECKS AND GIBLETS.],"Tyson Uncooked Whole Cornish Hens, 24/case"
1977395,2725770,Tyson Foods Inc.,Meat/Poultry/Other Animals - Prepared/Processed,"[CHICKEN WING SECTIONS, WATER]",Tyson Fully Cooked Unbreaded Oven Roasted Bone...
1977396,2725771,"Conagra Brands, Inc",Nuts/Seeds - Prepared/Processed,"[PUMPKIN SEED KERNELS, SEA SALT, HIGH OLEIC CA...","David Sea Salt Pumpkin Pepitas Seeds, Keto Fri..."
1977397,2725772,East Side Entrees,Dairy/Egg Based Products / Meals,"[YOGURT, LOW FAT, SUMMERBERRY: CULTURED PASTE...",Breakfast Kit Strawberry Yogurt

In [36]:
os.makedirs("D:/Downloads/Research/Data/processed", exist_ok=True)

In [34]:
import os

In [37]:
final_data.to_csv("D:/Downloads/Research/Data/processed/cleaned_usda_data.csv", index=False)

In [38]:
print("Total products after cleaning:", len(final_data))

Total products after cleaning: 1977398